# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yifei Liu
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "" # the subpath of the site
url: "https://yifei-liu-yl.github.io" # the base hostname & protocol for the site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
remote_theme: eliottvincent/bay
plugins:
  - jekyll-feed

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Publication
    - name: CV
    - name: Contact

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: yifei.violet.liu@wisc.edu
      link: mailto:yifei.violet.liu@wisc.edu
    # - name: WeChat
    #   value: YourWeChatUsername
      link: "#"
    - name: Address
      value: Taylor Hall, 427 Lorch Street, Madison, WI 53706
  follow:
    # - name: Twitter
    #   link: http://twitter.com/YourTwitterUsername
    #   username: "@YourTwitterUsername"
    # - name: Facebook
    #   link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: https://www.linkedin.com/in/yifei-liu-a56b67135/
    - name: GitHub
      link: https://github.com/yifei-liu-yl
    # - name: Dribbble
    #   link: https://dribbble.com/YourDribbbleUsername
    # - name: RSS
    #   link: /feed.xml
    - name: Orcid
      link: https://orcid.org/0000-0002-0103-2464
    - name: Scholar
      link: https://scholar.google.com/citations?hl=en&authuser=1&user=HXurJnUAAAAJ

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
