# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Taekho You
description: >- # this means to ignore newlines until "baseurl:"
  Taekho You's webpage.
baseurl: "/" # the subpath of the site
url: "https://th-and-you.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Publication
    - name: Work
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: taekho.you@ssu.ac.kr
      link: mailto:taekho.you@ssu.ac.kr
  follow:
    - name: Twitter
      link: http://twitter.com/thyou14
      username: "@thyou14"
    - name: LinkedIn
      link: http://linkedin.com/in/taekho-you-0883b0122
    - name: GoogleScholar
      link: https://scholar.google.com/citations?user=iforsrgAAAAJ&hl=ko
#    - name: Facebook
#      link: http://facebook.com/YourFacebookUsername
#    - name: GitHub
#      link: http://github.com/YourGitHubUsername
#    - name: Dribbble
#      link: https://dribbble.com/YourDribbbleUsername
#    - name: RSS
#      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
