# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yaoyu Liu's profile in Bay Jekyll Theme
description: >- # this means to ignore newlines until "baseurl:"
  Bay is a minimal Jekyll Theme.
baseurl: "/bay" # the subpath of the site
url: "https://journey1234-liu.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Homepage
      slug: /
    - name: Publication
    - name: Project
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: lyyu19@sjtu.edu.cn
      link: mailto:lyyu19@sjtu.edu.cn
  follow:
    - name: GitHub
      link: http://github.com/journey1234-liu

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
